[project]
name = "airmonitoring"
version = "0.1.0"
description = "AirGradient data collection and analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "duckdb>=1.4",
    "polars",
    "pyarrow",
    "pytz",
    "pyrefly",
    "requests",
    "typer",
    "vegafusion[embed]",
    "vl-convert-python",
    "ipykernel",
    "numpy>=2.3.4",
]

[dependency-groups]
ci = [
    "requests",
    "python-dotenv",
    "duckdb<=1.4.3",
    "polars",
    "pyarrow",
    "typer",
    "awscli",
    "pytz",
    "pyrefly",
]
