name: Download AirGradient Data

on:
  schedule:
    - cron: '0 0 */10 * *' # Runs every 10 days
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r actions-requirements.txt

      - name: Download data
        env:
          AIRGRADIENT_TOKEN: ${{ secrets.AIRGRADIENT_TOKEN }}
          AIRGRADIENT_LOCATION_ID: ${{ secrets.AIRGRADIENT_LOCATION_ID }}
        run: python airgradient_downloader.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
