name: Download AirGradient Data

on:
  schedule:
    - cron: '0 23 * * 0' # Runs every Sunday at 11PM
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Download data
        env:
          AIRGRADIENT_TOKEN: ${{ secrets.AIRGRADIENT_TOKEN }}
          AIRGRADIENT_LOCATION_ID: ${{ secrets.AIRGRADIENT_LOCATION_ID }}
        run: uv run --only-group ci python airgradient_downloader.py --save-csv

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
